name: names
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

version: 1.0.19+29

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  hexcolor: ^3.0.1
  extended_image: ^6.0.1
  #  connectivity: ^3.0.6 // is deprecated is replaced connectivity_plus
  connectivity_plus: ^3.0.2
  shared_preferences: ^2.0.6
  fluttertoast: ^8.2.1
  # don't update image_picker library
  image_picker: ^0.8.4+4
  flutter_launcher_icons: ^0.12.0
  introduction_screen: ^3.0.2
  percent_indicator: ^4.0.1
  readmore: ^2.1.0
  # don't update video_compress library
  flick_video_player: ^0.5.0
  visibility_detector: ^0.2.2
  popup_menu: ^1.0.5
  pin_code_fields: ^7.3.0
  file_picker:
  mime: ^1.0.0
  open_file_safe:
  carousel_slider: ^4.0.0
  date_format: ^2.0.2
  hmssdk_flutter: ^1.5.0
  dio:
#  open_file_safe: ^3.2.3
  firebase_core: ^2.4.1
  cloud_firestore: ^4.3.1
  firebase_auth: ^4.2.2
  firebase_analytics: ^10.1.0
  firebase_database: ^10.0.9
  firebase_messaging: ^14.2.1
  firebase_crashlytics: ^3.0.11
  intl: ^0.18.1
  emoji_picker_flutter: ^1.0.6
  flutter_keyboard_visibility: ^5.0.3
  uuid: ^3.0.4
  flutter_local_notifications: ^12.0.4
  linkedin_login: ^2.1.0
  google_sign_in: ^6.1.0

  permission_handler: ^10.2.0
  full_screen_image: ^2.0.0
  flutter_signin_button: ^2.0.0
  sound_mode: ^2.0.2
  webview_flutter: ^3.0.4
  url_launcher: ^6.1.2
  firebase_dynamic_links: ^5.0.11
  share_plus: ^4.0.4
  flutter_mute: ^0.0.4
  sign_in_with_apple: ^4.0.0
  flutter_html:
  cloud_functions: ^4.0.7
  photo_view: ^0.14.0
  flutter_callkit_incoming: ^1.0.3+3
  just_audio: ^0.9.24
  provider: ^6.0.5
  focus_detector: ^2.0.1
  wakelock: ^0.6.2
  http:
  link_text:
  flutter_staggered_grid_view: ^0.4.0
  flutter_switch: ^0.3.2
  upgrader:

  flutter_callkeep: ^0.3.1+1
  syncfusion_flutter_datepicker: ^21.1.41
  native_device_orientation: ^1.1.4
  after_layout: ^1.1.0
  collection:
  device_info_plus: ^4.0.0
  flutter_svg: ^2.0.5
  syncfusion_flutter_calendar: ^21.2.4
  google_place: ^0.4.7
  video_compress: ^3.0.0
  chunked_uploader:
  flutter_upchunk:
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/launcher_icon.jpg"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/audio/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  fonts:
    - family: Roboto_Regular
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: Roboto_Black
      fonts:
        - asset: assets/fonts/Roboto-Black.ttf
    - family: Roboto_Bold
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
    - family: Lato_Regular
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
    - family: Lato_BoldItalic
      fonts:
        - asset: assets/fonts/Lato-BoldItalic.ttf
    - family: Lato_Bold
      fonts:
        - asset: assets/fonts/Lato-Bold.ttf
    - family: Lato_Italic
      fonts:
        - asset: assets/fonts/Lato-Italic.ttf
    #  fonts:
    #       fonts:    #     - family: Zimra
    #         - asset: assets/fonts/Zimra-Black.ttf
    #         - asset: assets/fonts/Zimra-Bold.ttf
    #   - family: Trajan Pro
    #     fonts:
    #       - asset: fonts/TrajanPro.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700
    #
    # For details regarding fonts from package dependencies,
    # see https://flutter.dev/custom-fonts/#from-packages
