// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADdJkoAb8I8TtoZ5lfxSsIji2wCTRz3yg',
    appId: '1:12737140720:android:52eac57d1f237c87752f35',
    messagingSenderId: '12737140720',
    projectId: 'names-c6545',
    storageBucket: 'names-c6545.appspot.com',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDL2ui6VdzTH3pXcHKvKVo4QamYknK3mVA',
    appId: '1:12737140720:ios:914c3c59a621558b752f35',
    messagingSenderId: '12737140720',
    projectId: 'names-c6545',
    storageBucket: 'names-c6545.appspot.com',
    androidClientId: '12737140720-37kdqjajoluops5793q4ebimo00lm99v.apps.googleusercontent.com',
    iosClientId: '12737140720-ngqsajr0b07go4tdhfavr0rljklbsaju.apps.googleusercontent.com',
    iosBundleId: 'com.names.io',
  );
}
